/* ifcvt_test.c - Target the uncovered lines in ifcvt.cc */
#include <stdio.h>
#include <stdlib.h>

/* Global variables to create complex condition expressions */
static volatile int global_cond = 0;
static volatile int threshold = 5;
static volatile int* volatile ptr = NULL;
static int data_array[10] = {0};

/* Function to prevent optimization */
__attribute__((noinline, noclone))
static int use_value(int x) {
    asm volatile("" : "+r"(x) : : "memory");
    return x;
}

/* Function with the targeted if-then-else structure */
__attribute__((noinline, noclone, target("default")))
static int test_if_conversion(int x, int y) {
    int result = 0;
    
    /* Force pointer setup */
    ptr = &data_array[0];
    *ptr = x;
    
    /* Complex condition: global variable + pointer dereference */
    if (global_cond > 0 && *ptr < threshold) {
        /* 
         * HEADER SECTION OF THEN BLOCK:
         * 1. Starts with implicit label (generated by GCC)
         * 2. We'll add debug/note instructions via asm
         * 3. Modify condition variable BEFORE first real instruction
         */
        
        /* Generate NOTE/DEBUG_INSN via asm comments */
        asm volatile("# DEBUG/NOTE: Entering then block");
        asm volatile("# Another note instruction");
        
        /* CRITICAL: Modify global_cond used in condition - this should be 
           in the header before then_last_head */
        global_cond = x + y;  /* This modifies test_expr! */
        
        /* Generate more notes to ensure header has multiple instructions */
        asm volatile("# More debug info here");
        
        /*
         * Now the "real" instructions begin after the header.
         * This should be where then_last_head points.
         */
        int temp = use_value(x);
        
        /* Additional instructions to make block non-trivial */
        for (int i = 0; i < 3; i++) {
            data_array[i] = temp + i;
            result += data_array[i];
        }
        
        /* More operations to prevent block merging */
        result *= 2;
        result -= y;
        
        /* Memory barrier to prevent reordering */
        asm volatile("" : : : "memory");
    } else {
        /* Else block with different computation */
        result = y * 2;
        global_cond = y - x;
    }
    
    /* Use result to prevent dead code elimination */
    return result + global_cond;
}

/* Another test case with different condition structure */
__attribute__((noinline, noclone))
static int test_case2(int a, int b) {
    static volatile int static_var = 0;
    volatile int local_volatile = a;
    
    /* Compound condition with static variable */
    if ((static_var > 10) || (local_volatile < b)) {
        /* Header with notes */
        asm volatile("# Test case 2 header note 1");
        asm volatile("# Test case 2 header note 2");
        
        /* Modify static_var used in condition */
        static_var = a * b;  /* Modification in header */
        
        /* More notes */
        asm volatile("# Additional debug info");
        
        /* Real computation */
        int sum = 0;
        for (int i = 0; i < 4; i++) {
            sum += a + i * b;
        }
        return sum;
    }
    
    return a - b;
}

/* Main function to exercise the code */
int main(void) {
    int total = 0;
    
    /* Initialize */
    global_cond = 1;
    threshold = 10;
    
    /* Call multiple times with different inputs */
    for (int i = 0; i < 100; i++) {
        /* Vary inputs to exercise both paths */
        if (i % 3 == 0) {
            global_cond = -1;  /* Force else path sometimes */
        } else {
            global_cond = i % 7 + 1;  /* Force then path */
        }
        
        total += test_if_conversion(i, i * 2);
        total += test_case2(i, i + 1);
    }
    
    printf("Result: %d\n", total);
    return total != 0 ? 0 : 1;
}
