/* ifcvt_coverage.c
 * Target: Trigger uncovered lines 577-583 in ifcvt.cc
 * Compile with: gcc -O2 -fdump-rtl-ifcvt -fdump-rtl-all ifcvt_coverage.c -o ifcvt_coverage
 * For ARM: gcc -O3 -march=armv7-a -mtune=cortex-a9 -fdump-rtl-ifcvt ifcvt_coverage.c
 */

#include <stdio.h>
#include <stdlib.h>

/* Global variables to create complex condition expressions */
static volatile int global_cond = 0;
static int* volatile global_ptr = NULL;
static int threshold = 100;

/* Function to prevent optimization */
static int __attribute__((noinline, noclone)) 
use_result(int val) {
    volatile int sink = val;
    return sink;
}

/* Test function with the critical if-then-else structure */
static int __attribute__((noinline, noclone))
test_if_conversion(int a, int b, int* ptr) {
    int result = 0;
    
    /* Complex condition using global variable and pointer dereference */
    if (global_cond > threshold && *ptr != 0 && a < b) {
        /* 
         * This then-block should have:
         * 1. A label at the start (generated by GCC)
         * 2. Potential NOTE/DEBUG_INSN instructions from asm statements
         * 3. Modification of condition variable BEFORE first real instruction
         */
        
        /* Generate NOTE/DEBUG_INSN instructions in header */
        asm volatile("# THEN BLOCK HEADER - NOTE 1");
        asm volatile("# THEN BLOCK HEADER - NOTE 2");
        
        /* CRITICAL: Modify global_cond which is part of the condition expression
         * This happens in the block header before then_last_head */
        global_cond = 50;  /* Direct modification of condition variable */
        
        /* Additional asm to ensure notes in header */
        asm volatile("# AFTER MODIFICATION - NOTE 3");
        
        /* Now the "real" instructions begin */
        result = a * b + global_cond;
        
        /* More operations to ensure block has multiple instructions */
        *ptr = result;
        global_ptr = ptr;
        
        /* Function call to create complex RTL */
        result = use_result(result);
        
        /* Additional operations */
        for (int i = 0; i < 3; i++) {
            result += i;
        }
    } else {
        /* Else block with different operations */
        result = b - a;
        global_cond = threshold + 10;
    }
    
    return result;
}

/* Another test case with pointer-based condition */
static int __attribute__((noinline, noclone))
test_pointer_condition(int x, int y) {
    static int data[10] = {0};
    int* ptr = &data[0];
    int result = 0;
    
    /* Condition using pointer dereference */
    if (*ptr + x > y && global_cond < 200) {
        /* Header with notes and modification */
        asm volatile("# POINTER TEST HEADER");
        
        /* Modify through pointer - affects condition */
        *ptr = x * 2;  /* This modifies *ptr used in condition */
        
        asm volatile("# AFTER POINTER MOD");
        
        /* Real work */
        result = *ptr + y;
        for (int i = 0; i < 5; i++) {
            data[i] = result + i;
        }
    } else {
        result = y - x;
        *ptr = result;
    }
    
    return result;
}

/* Test with volatile to prevent reordering */
static int __attribute__((noinline, noclone))
test_volatile_modification(int val) {
    volatile int cond_var = val;
    int temp = 0;
    
    /* Condition using volatile variable */
    if (cond_var > 50 && global_cond != 0) {
        /* Notes in header */
        asm volatile("# VOLATILE HEADER START");
        
        /* Modify condition variable */
        cond_var = 25;  /* Direct modification */
        
        asm volatile("# AFTER VOLATILE MOD");
        
        /* Real instructions */
        temp = cond_var * 2;
        global_cond = temp;
        
        /* Loop to create more instructions */
        for (int i = 0; i < 4; i++) {
            temp += i + global_cond;
        }
    } else {
        temp = val * 3;
        cond_var = temp;
    }
    
    return temp;
}

int main(void) {
    int data = 42;
    int* ptr = &data;
    int results[3] = {0};
    
    /* Initialize globals */
    global_cond = 75;
    global_ptr = ptr;
    
    /* Test 1: Trigger modification in then-block header */
    printf("Test 1: global_cond = %d, threshold = %d\n", global_cond, threshold);
    results[0] = test_if_conversion(10, 20, ptr);
    printf("Result 1: %d, global_cond now: %d\n", results[0], global_cond);
    
    /* Test 2: Different branch */
    global_cond = 150;  /* Will take else branch */
    results[1] = test_if_conversion(30, 20, ptr);
    printf("Result 2: %d, global_cond now: %d\n", results[1], global_cond);
    
    /* Test 3: Pointer-based condition */
    results[2] = test_pointer_condition(15, 25);
    printf("Result 3: %d\n", results[2]);
    
    /* Test 4: Volatile modification */
    int vol_result = test_volatile_modification(60);
    printf("Result 4: %d\n", vol_result);
    
    /* Additional calls to ensure compiler generates code */
    for (int i = 0; i < 5; i++) {
        global_cond = i * 50;
        test_if_conversion(i, i*2, ptr);
    }
    
    return use_result(results[0] + results[1] + results[2]);
}
