/* ifcvt_coverage.c - Target for GCC if-conversion pass coverage */
/* Compile with: gcc -O2 -fdump-rtl-ifcvt -S ifcvt_coverage.c */
/* Or for ARM: gcc -O2 -march=armv7-a -mtune=cortex-a9 -fdump-rtl-ifcvt -S ifcvt_coverage.c */

#include <stdio.h>
#include <stdint.h>

/* Global variables to create non-trivial condition expressions */
static volatile int global_cond = 0;
static volatile int global_threshold = 100;
static volatile int* global_ptr = NULL;
static int global_array[10] = {0};

/* Function to prevent optimizations */
static int __attribute__((noinline, noclone)) 
use_value(int x) {
    volatile int sink = x;
    return sink;
}

/* Function with complex condition that will be modified in the then block header */
static int __attribute__((noinline, noclone))
test_if_conversion(int a, int b) {
    int result = 0;
    
    /* Complex condition using global variable - creates non-trivial test_expr */
    /* The condition uses global_cond which will be modified in the then block */
    if (global_cond > global_threshold && a < b) {
        /* This is the then_bb block */
        /* The block starts with a label (generated by GCC) */
        
        /* Generate NOTE or DEBUG_INSN instructions using asm comments */
        /* These should appear before the first "real" instruction in RTL */
        asm volatile("# DEBUG/NOTE: Entering then block");
        asm volatile("# Another note instruction");
        
        /* CRITICAL: Modify the condition variable BEFORE any other real instruction */
        /* This modification happens in the block's header section */
        global_cond = 50;  /* This modifies test_expr used in the condition */
        
        /* Compiler barrier to prevent reordering */
        asm volatile("" : : : "memory");
        
        /* More NOTE/DEBUG instructions after modification */
        asm volatile("# DEBUG: After modifying condition");
        
        /* Additional statements to create a multi-instruction block */
        /* These come after then_last_head in the RTL representation */
        result = a + b;
        global_array[0] = result;
        
        /* Use volatile asm to generate more notes */
        asm volatile("# Processing result: %0" : : "r"(result));
        
        result = use_value(result * 2);
        
        /* Another modification to ensure block has side effects */
        global_ptr = &global_array[1];
        *global_ptr = result;
        
    } else {
        /* else block */
        result = a - b;
        global_cond++;  /* Modify global_cond differently */
    }
    
    return result;
}

/* Another test with pointer-based condition */
static int __attribute__((noinline, noclone))
test_pointer_condition(int x) {
    static volatile int data = 0;
    volatile int* ptr = &data;
    int local_result = 0;
    
    /* Condition based on pointer dereference */
    if (*ptr > x && global_threshold < 200) {
        /* Block header with notes */
        asm volatile("# NOTE: Pointer condition block");
        
        /* Modify through the pointer - affects the condition expression */
        *ptr = x - 10;  /* This modifies what was dereferenced in condition */
        
        asm volatile("# DEBUG: After pointer modification");
        asm volatile("" : : : "memory");
        
        /* Real work after modification */
        local_result = x * 2;
        for (int i = 0; i < 3; i++) {
            local_result += i;
        }
        
        /* Additional global side effect */
        global_threshold = local_result;
        
    } else {
        local_result = x / 2;
        *ptr = local_result;
    }
    
    return local_result;
}

/* Test with compound condition where one part is modified */
static int __attribute__((noinline, noclone))
test_compound_condition(int a, int b, int c) {
    volatile static int cond1 = 0;
    volatile static int cond2 = 0;
    int res = 0;
    
    /* Compound condition */
    if ((cond1 > a) && (cond2 < b) && (global_cond != c)) {
        /* Multiple notes/debug insns in header */
        asm volatile("# Compound condition block start");
        asm volatile("# Another note");
        asm volatile("# Yet another note");
        
        /* Modify one part of the compound condition */
        cond1 = b;  /* This affects test_expr */
        
        asm volatile("# After modifying cond1");
        asm volatile("" : : : "memory");
        
        /* Additional code to make block non-trivial */
        res = a * b * c;
        for (int i = 0; i < 5; i++) {
            res += global_array[i % 10];
        }
        
        /* Call to external function to create complex RTL */
        res = use_value(res);
        
    } else {
        res = a + b + c;
        cond1 = a;
        cond2 = b;
    }
    
    return res;
}

/* Main function to exercise all test cases */
int main(void) {
    int total = 0;
    
    /* Initialize globals */
    global_cond = 150;  /* Will satisfy first condition */
    global_threshold = 100;
    global_array[0] = 42;
    
    /* Call multiple times with different parameters to exercise different paths */
    for (int i = 0; i < 10; i++) {
        /* First call: should take then branch (global_cond > threshold) */
        total += test_if_conversion(i, i * 2);
        
        /* Change condition to exercise else branch */
        global_cond = 50;
        total += test_if_conversion(i * 3, i);
        
        /* Test pointer condition */
        total += test_pointer_condition(i + 10);
        
        /* Test compound condition */
        total += test_compound_condition(i, i + 1, i + 2);
        
        /* Vary global threshold to change branch behavior */
        global_threshold += i;
    }
    
    /* Use the result to prevent dead code elimination */
    printf("Result: %d\n", total);
    
    return total > 0 ? 0 : 1;
}
