/* ifcvt_test.c - Test case for GCC if-conversion pass coverage */
#include <stdio.h>
#include <stdlib.h>

/* Global variables to create complex condition expressions */
static volatile int global_cond = 0;
static volatile int threshold = 5;
static volatile int* volatile ptr = NULL;
static volatile int data[10] = {0};

/* Function to prevent optimization */
__attribute__((noinline, noclone))
static int use_result(int val) {
    volatile int sink = val;
    return sink;
}

/* Target function with the specific if-then-else structure */
__attribute__((noinline, noclone, optimize("O2")))
int test_if_conversion(int x, int y) {
    volatile int local_mod = x;
    int result = 0;
    
    /* Complex condition using global variable */
    if (global_cond < threshold) {
        /* HEADER SECTION START (target for uncovered lines) */
        /* This label will be generated by GCC for the block start */
        
        /* Generate NOTE/DEBUG_INSN instructions using asm comments */
        asm volatile("# DEBUG/NOTE: Beginning of then block header");
        asm volatile("# Another note instruction");
        
        /* CRITICAL: Modify the condition variable BEFORE any real instruction
           This should be in the header before then_last_head */
        global_cond = x + y;  /* Modifies test_expr used in condition */
        
        /* Compiler barrier to prevent reordering */
        asm volatile("" : : : "memory");
        
        /* More notes/debug insns after modification */
        asm volatile("# DEBUG/NOTE: After condition modification");
        
        /* HEADER SECTION END - now real instructions begin */
        
        /* Real computation after header */
        result = x * y + global_cond;
        
        /* Additional operations to ensure block has multiple instructions */
        ptr = &local_mod;
        *ptr = result;
        data[0] = *ptr + 1;
        
        /* Function call to create more complex RTL */
        result = use_result(result);
        
    } else {
        /* Else branch with different computation */
        result = x - y;
        global_cond = result / 2;
    }
    
    /* Use result to prevent dead code elimination */
    return use_result(result);
}

/* Second test with pointer-based condition */
__attribute__((noinline, noclone, optimize("O2")))
int test_pointer_condition(int x) {
    static volatile int* cond_ptr = NULL;
    static volatile int cond_data = 0;
    
    /* Initialize pointer first */
    if (cond_ptr == NULL) {
        cond_ptr = &cond_data;
        cond_data = 3;
    }
    
    int result = 0;
    
    /* Condition with pointer dereference */
    if (*cond_ptr > 0 && x < 10) {
        /* Header with notes */
        asm volatile("# Note: Pointer condition block");
        
        /* Modify through pointer - affects condition expression */
        *cond_ptr = x * 2;  /* Modifies memory referenced in condition */
        
        asm volatile("# Note: After pointer modification");
        asm volatile("" : : : "memory");
        
        /* Real computation */
        result = x + *cond_ptr;
        
        /* More operations */
        for (int i = 0; i < 3; i++) {
            data[i] = result + i;
        }
        
    } else {
        result = x * 3;
        *cond_ptr = result;
    }
    
    return use_result(result);
}

/* Third test with compound condition */
__attribute__((noinline, noclone, optimize("O2")))
int test_compound_condition(int a, int b, int c) {
    volatile static int counter = 0;
    int result = 0;
    
    /* Compound condition where one part gets modified */
    if (a > b && counter < 5) {
        /* Header section */
        asm volatile("# Compound condition block header");
        
        /* Modify part of the compound condition */
        counter = a + b;  /* Modifies counter used in condition */
        
        asm volatile("# After counter modification");
        asm volatile("" : : : "memory");
        
        /* Real work */
        result = (a - b) * c;
        
        /* Loop to create more instructions */
        for (int i = 0; i < 4; i++) {
            result += data[i];
        }
        
    } else {
        result = b - a;
        counter = result;
    }
    
    return use_result(result);
}

/* Main function to exercise all test cases */
int main(void) {
    int total = 0;
    
    /* Initialize global data */
    global_cond = 0;
    threshold = 5;
    
    /* Call test functions multiple times with different inputs
       to ensure if-conversion pass is invoked */
    for (int i = 0; i < 10; i++) {
        total += test_if_conversion(i, i + 1);
        total += test_pointer_condition(i);
        total += test_compound_condition(i, i - 1, i + 2);
        
        /* Vary global condition to take different paths */
        global_cond = (i % 3) * 2;
        threshold = (i % 4) + 3;
    }
    
    printf("Result: %d\n", total);
    return total != 0 ? 0 : 1;
}
