/* ifcvt_test.c - Target the uncovered lines 577-583 in ifcvt.cc */
#include <stdio.h>
#include <stdlib.h>

/* Global variables to create complex condition expressions */
static volatile int global_cond = 0;
static volatile int threshold = 5;
static volatile int* volatile ptr = NULL;
static int data_array[10] = {0};

/* Function attributes to prevent optimization */
__attribute__((noinline, noclone, noipa))
#ifdef __x86_64__
__attribute__((target("arch=x86-64")))
#elif defined(__arm__)
__attribute__((target("arch=armv7-a")))
#endif
int test_if_conversion(int x, int y) {
    volatile int local_mod = 0;
    int result = 0;
    
    /* Complex condition using global variable and pointer dereference */
    /* This should generate a non-trivial test_expr in RTL */
    if (global_cond < threshold && (ptr != NULL ? *ptr : 0) > 0) {
        /* 
         * HEADER SECTION OF THEN BLOCK:
         * The block starts with a label (generated by GCC)
         * We need instructions before then_last_head that modify test_expr
         */
        
        /* Generate NOTE/DEBUG_INSN with asm comments */
        asm volatile("# DEBUG/NOTE: Start of then block header");
        asm volatile("# Another note instruction");
        
        /* CRITICAL: Modify global_cond which is part of the condition
         * This happens BEFORE any real instruction in the block
         * This should be detected by modified_in_p(test_expr, insn)
         */
        global_cond = x + y;  /* Modifies variable used in condition */
        
        /* More notes/debug to ensure we're in header section */
        asm volatile("# DEBUG/NOTE: After modification");
        
        /* 
         * This is the first "real" instruction after header.
         * then_last_head should point to this or similar.
         */
        local_mod = x * y;
        
        /* Additional instructions to make block non-trivial */
        result = local_mod + global_cond;
        data_array[result % 10] = result;
        
        /* More operations to ensure sufficient instructions */
        for (int i = 0; i < 3; i++) {
            result += data_array[i];
        }
        
        /* Use result to prevent dead code elimination */
        asm volatile("" : "+r" (result) : : "memory");
    } else {
        /* Else branch with different computation */
        result = x - y;
        global_cond = result / 2;
        data_array[0] = result;
    }
    
    /* Compiler barrier to prevent reordering */
    asm volatile("" : : : "memory");
    
    return result;
}

/* Another test function with different condition pattern */
__attribute__((noinline, noclone, noipa))
int test_pointer_modification(int* arr, int size) {
    static volatile int counter = 0;
    int sum = 0;
    
    /* Condition with pointer arithmetic */
    if (arr != NULL && size > 0 && counter < 10) {
        /* Header with notes */
        asm volatile("# Note 1 in header");
        asm volatile("# Note 2 in header");
        
        /* Modify counter used in condition */
        counter = size % 5;
        
        /* More notes */
        asm volatile("# Note 3: after counter modification");
        
        /* Real computation starts here */
        for (int i = 0; i < size && i < 10; i++) {
            sum += arr[i];
        }
        
        /* Additional modification to condition variable */
        if (sum > 100) {
            counter = 20;  /* Another modification */
        }
    } else {
        sum = -1;
        counter = 0;
    }
    
    return sum;
}

/* Function to ensure complex condition expression */
__attribute__((noinline, noclone, noipa))
int test_compound_condition(int a, int b, int c) {
    volatile static int mod_target = 0;
    int res = 0;
    
    /* Compound condition with multiple variables */
    if ((a > b) && (b < c) && (mod_target == 0)) {
        /* Header section */
        asm volatile("# Compound condition block header");
        
        /* Modify variable used in condition */
        mod_target = a + b + c;
        
        asm volatile("# After mod_target assignment");
        
        /* Real work */
        res = mod_target * 2;
        
        /* Complex computation to prevent optimization */
        for (int i = 0; i < 5; i++) {
            res += i * mod_target;
            asm volatile("# Loop iteration %0" : : "r" (i));
        }
    } else {
        res = a - b - c;
        mod_target = res;
    }
    
    return res;
}

int main(void) {
    int results[3] = {0};
    int test_data[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    
    /* Initialize global variables */
    global_cond = 3;
    threshold = 5;
    ptr = &global_cond;
    
    printf("Testing if-conversion with early condition modification...\n");
    
    /* Multiple calls to trigger if-conversion pass */
    for (int i = 0; i < 10; i++) {
        /* Vary inputs to exercise different paths */
        results[0] = test_if_conversion(i, i * 2);
        results[1] = test_pointer_modification(test_data, i % 10);
        results[2] = test_compound_condition(i, i + 1, i + 2);
        
        /* Modify global between calls */
        global_cond = (global_cond + 1) % 10;
        ptr = (i % 3 == 0) ? NULL : &global_cond;
    }
    
    /* Use results to prevent dead code elimination */
    int final_result = 0;
    for (int i = 0; i < 3; i++) {
        final_result += results[i];
    }
    
    printf("Final result: %d\n", final_result);
    printf("Global cond: %d\n", global_cond);
    
    return final_result != 0 ? 0 : 1;
}
