/* ifcvt-test.c - Test case for GCC if-conversion pass coverage */
#include <stdio.h>
#include <stdlib.h>

/* Global variables to create complex condition expressions */
static volatile int global_cond = 0;
static int* volatile global_ptr = NULL;
static int threshold = 100;
static int side_effect_counter = 0;

/* Function to prevent optimizations */
static int __attribute__((noinline, noclone)) 
helper_func(int x) {
    return x * 2 + 1;
}

/* Function with volatile asm to generate NOTE/DEBUG_INSN */
static void __attribute__((used)) 
emit_note(void) {
    /* These asm statements generate NOTE/DEBUG_INSN in RTL */
    asm volatile("# BRANCH HEADER NOTE 1");
    asm volatile("# BRANCH HEADER NOTE 2");
    asm volatile("# DEBUG NOTE FOR HEADER");
}

/* Target function containing the critical if-then-else structure */
static int __attribute__((noinline, noclone))
test_if_conversion(int a, int b, int* out) {
    int result = 0;
    
    /* Complex condition using global variable and pointer dereference */
    if (global_cond > threshold && *global_ptr != 0) {
        /* 
         * This then-block header should contain:
         * 1. A label (generated by GCC)
         * 2. NOTE/DEBUG_INSN from emit_note()
         * 3. Modification of condition variable BEFORE first real instruction
         */
        emit_note();  /* Generates NOTE/DEBUG_INSN in header */
        
        /* CRITICAL: Modify condition variable in header before other instructions */
        global_cond = 50;  /* This modifies test_expr used in condition */
        
        /* Compiler barrier to prevent reordering */
        asm volatile("" : : : "memory");
        
        /* Additional instructions to create multi-instruction block */
        result = helper_func(a);
        *out = result + b;
        side_effect_counter++;
        
        /* More operations to ensure block is substantial */
        for (int i = 0; i < 3; i++) {
            *out += i;
        }
    } else {
        /* Else block with different behavior */
        result = helper_func(b);
        *out = result - a;
        global_cond += 10;
    }
    
    return result;
}

/* Alternate version with different condition structure */
static int __attribute__((noinline, noclone))
test_if_conversion2(int x, int y) {
    static int static_var = 0;
    int local_result = 0;
    
    /* Condition using static variable */
    if (static_var > 0 && global_ptr != NULL) {
        /* Header with notes and modification */
        asm volatile("# HEADER NOTE A");
        asm volatile("# HEADER NOTE B");
        
        /* Modify static_var which is part of condition */
        static_var = x - y;  /* Modification in header */
        
        /* Memory barrier */
        asm volatile("" : : : "memory");
        
        /* Body of then-block */
        local_result = x * y;
        if (global_ptr) {
            *global_ptr = local_result;
        }
        side_effect_counter += 2;
    } else {
        local_result = x + y;
        static_var += 5;
    }
    
    return local_result;
}

/* Main function to exercise the if-conversion paths */
int main(void) {
    int buffer[10];
    int* ptr = &buffer[5];
    int results[4];
    
    /* Initialize global variables */
    global_ptr = ptr;
    *global_ptr = 42;  /* Non-zero value */
    global_cond = 150; /* Greater than threshold */
    
    printf("Testing if-conversion scenarios...\n");
    
    /* Test 1: Should take then-branch */
    results[0] = test_if_conversion(10, 20, &buffer[0]);
    printf("Test 1: result=%d, buffer[0]=%d, global_cond=%d\n", 
           results[0], buffer[0], global_cond);
    
    /* Test 2: Change condition to take else-branch */
    global_cond = 50;  /* Less than threshold */
    results[1] = test_if_conversion(30, 40, &buffer[1]);
    printf("Test 2: result=%d, buffer[1]=%d, global_cond=%d\n", 
           results[1], buffer[1], global_cond);
    
    /* Test 3: Use second test function */
    global_ptr = NULL;  /* Force else-branch */
    results[2] = test_if_conversion2(5, 7);
    printf("Test 3: result=%d, side_effect=%d\n", 
           results[2], side_effect_counter);
    
    /* Test 4: Take then-branch in second function */
    global_ptr = ptr;
    results[3] = test_if_conversion2(8, 3);
    printf("Test 4: result=%d, side_effect=%d\n", 
           results[3], side_effect_counter);
    
    /* Additional loop to increase execution frequency */
    for (int i = 0; i < 100; i++) {
        global_cond = i;
        threshold = 50;
        test_if_conversion(i, i*2, &buffer[i % 10]);
    }
    
    printf("All tests completed. side_effect_counter=%d\n", side_effect_counter);
    return 0;
}
