/* ifcvt_test.c - Test case for if-conversion header modification check */

#include <stdio.h>
#include <stdlib.h>

/* Global variables to create non-trivial condition expressions */
static volatile int global_cond = 0;
static volatile int global_threshold = 5;
static volatile int* global_ptr = NULL;
static int global_array[10] = {0};

/* Function to prevent optimizations */
__attribute__((noinline, noclone))
static int use_value(int val) {
    volatile int sink = val;
    return sink;
}

/* Function with complex condition that will be modified in the then block header */
__attribute__((noinline, noclone))
int test_if_conversion(int x, int y) {
    int result = 0;
    
    /* Complex condition using global variable and pointer dereference */
    /* This creates a non-trivial test_expr for if-conversion */
    if (global_cond > global_threshold && global_ptr != NULL && *global_ptr < 10) {
        /* 
         * This block starts with a label (generated by GCC).
         * We need to modify the condition expression in the header portion.
         * The header includes everything up to the first non-label, non-note,
         * non-debug instruction that is not then_last_head.
         */
        
        /* Generate a NOTE or DEBUG_INSN first */
        asm volatile("# HEADER: This comment becomes a NOTE instruction");
        
        /* 
         * CRITICAL: Modify a variable used in the condition BEFORE any
         * other "real" instruction. This should be in the header portion.
         * We modify global_cond which is part of the condition.
         */
        global_cond = x;  /* This modifies test_expr! */
        
        /* Generate another note to ensure we're still in header */
        asm volatile("# Still in header");
        
        /* 
         * Now add some real work to create a proper basic block.
         * This should be after then_last_head in the RTL representation.
         */
        result = x * y + global_array[0];
        
        /* More operations to ensure block is substantial */
        global_array[0] = result % 100;
        if (global_ptr) {
            *global_ptr = result;
        }
        
        /* Call a function to prevent tail merging */
        result = use_value(result);
    } else {
        /* Else branch with different computation */
        result = x - y;
        global_cond = y;  /* Also modify here to prevent hoisting */
    }
    
    return result;
}

/* Another test case with different condition pattern */
__attribute__((noinline, noclone))
int test_pointer_condition(int val) {
    static int local_static = 0;
    int* ptr = &local_static;
    int result = 0;
    
    /* Condition using pointer dereference */
    if (*ptr > 0 && global_cond < 100) {
        /* Note/comment first */
        asm volatile("# Pointer test header");
        
        /* Modify through the pointer - affects the condition! */
        *ptr = val;  /* This modifies *ptr which is in test_expr */
        
        /* Another note */
        asm volatile("# Still in pointer header");
        
        /* Real work */
        result = val * 2;
        global_cond = result;
        
        /* Complex enough to not be optimized away */
        for (int i = 0; i < 3; i++) {
            result += i;
        }
    } else {
        result = val / 2;
        *ptr = result;
    }
    
    return result;
}

/* Test with compound condition where only part is modified */
__attribute__((noinline, noclone))
int test_partial_modification(int a, int b) {
    volatile int cond1 = a;
    static int cond2 = 0;
    int result = 0;
    
    /* Compound condition - only cond2 will be modified in header */
    if (cond1 > 0 && cond2 < 10) {
        /* Header notes */
        asm volatile("# Partial mod header 1");
        asm volatile("# Partial mod header 2");
        
        /* Modify only cond2, not cond1 */
        cond2 = b;  /* cond2 is part of test_expr */
        
        /* Real work */
        result = a + b + cond2;
        
        /* Ensure block has multiple instructions */
        result *= 2;
        result -= a;
        global_array[1] = result;
    } else {
        result = a - b;
        cond2 = a;
    }
    
    return result;
}

int main(void) {
    int results[3] = {0};
    int test_data[][2] = {{10, 3}, {2, 8}, {7, 4}, {1, 9}};
    
    /* Initialize globals */
    global_cond = 3;
    global_threshold = 2;
    int local_var = 20;
    global_ptr = &local_var;
    *global_ptr = 5;
    
    printf("Testing if-conversion header modification check...\n");
    
    /* Call test functions multiple times with different inputs
     * to ensure if-conversion pass runs */
    for (int i = 0; i < 4; i++) {
        results[0] += test_if_conversion(test_data[i][0], test_data[i][1]);
        results[1] += test_pointer_condition(test_data[i][0]);
        results[2] += test_partial_modification(test_data[i][0], test_data[i][1]);
        
        /* Change global state to take different paths */
        global_cond += 5;
        if (global_ptr) {
            *global_ptr += 2;
        }
    }
    
    printf("Results: %d, %d, %d\n", results[0], results[1], results[2]);
    
    /* Use results to prevent dead code elimination */
    volatile int final_result = results[0] + results[1] + results[2];
    return final_result > 0 ? 0 : 1;
}
