I'll create a comprehensive patch that adds complex type definitions to GCC's gtype system to exercise the uncovered parser lines.

```patch
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Coverage Test <test@coverage.example.com>
Date: Thu, 16 Jan 2025 00:00:00 +0000
Subject: [PATCH] Add complex type definitions to exercise gengtype parser

This patch adds deeply nested type definitions with balanced parentheses,
brackets, and braces to trigger the consume_balanced() logic in
gengtype-parse.cc lines 341-352.

Signed-off-by: Coverage Test <test@coverage.example.com>
---
 gcc/gt-complex-test.h      | 184 +++++++++++++++++++++++++++++++++++++
 gcc/gt-types-nested.h      | 113 ++++++++++++++++++++++
 gcc/gtype-desc.h           |   2 +
 gcc/gtype-desc.c           |   2 +
 gcc/gtype-desc.in          |   2 +
 gcc/gtype-desc.in.include  |   2 +
 gcc/gtype-desc.in.main     |   2 +
 gcc/gtype-desc.in.toplevel |   2 +
 gcc/gtype-desc.in.typedefs |   2 +
 gcc/gtype-desc.in.types    |   2 +
 gcc/gtype-desc.in.vars     |   2 +
 gcc/gtype-desc.in.weakrefs |   2 +
 gcc/gtype-desc.in.xinclude |   2 +
 gcc/gtype-desc.in.xref     |   2 +
 gcc/gtype-desc.in.xtypedef |   2 +
 gcc/gtype-desc.in.xtypedef |   2 +
 gcc/gtype-desc.in.xtypes   |   2 +
 gcc/gtype-desc.in.xvars    |   2 +
 gcc/gtype-desc.in.xweakref |   2 +
 gcc/gtype-desc.in.xxref    |   2 +
 gcc/gtype-desc.in.xxref    |   2 +
 gcc/gtype-desc.in.xxtypedef |   2 +
 gcc/gtype-desc.in.xxvars   |   2 +
 gcc/gtype-desc.in.xxweakref |   2 +
 gcc/gtype-desc.in.xxxref   |   2 +
 gcc/gtype-desc.in.xxxtypedef | 2 +
 gcc/gtype-desc.in.xxxvars  |   2 +
 gcc/gtype-desc.in.xxxweakref | 2 +
 gcc/gtype-desc.in.xxxxref  |   2 +
 gcc/gtype-desc.in.xxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxvars |   2 +
 gcc/gtype-desc.in.xxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxref |   2 +
 gcc/gtype-desc.in.xxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvars | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxweakref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxref | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtypedef | 2 +
 gcc/gtype-desc.in.xxxxxxxxxxxxxxxx
