_CMP_EQ_OQ, _CMP_LT_OS, _CMP_LE_OS, _CMP_UNORD_Q, 
_CMP_NEQ_UQ, _CMP_NLT_US, _CMP_NLE_US, _CMP_ORD_Q,
_CMP_EQ_UQ, _CMP_NGE_US, _CMP_NGT_US, _CMP_FALSE_OQ,
_CMP_NEQ_OQ, _CMP_GE_OS, _CMP_GT_OS, _CMP_TRUE_UQ,
_CMP_EQ_OS, _CMP_LT_OQ, _CMP_LE_OQ, _CMP_UNORD_S,
_CMP_NEQ_US, _CMP_NLT_UQ, _CMP_NLE_UQ, _CMP_ORD_S,
_CMP_EQ_US, _CMP_NGE_UQ, _CMP_NGT_UQ, _CMP_FALSE_OS,
_CMP_NEQ_OS, _CMP_GE_OQ, _CMP_GT_OQ, _CMP_TRUE_US
