- Checks if `exp` is **not** an lvalue (i.e., it's an xvalue or prvalue)
- `lvalue_p()` likely returns true for lvalues, false for xvalues/prvalues
- `xval` will be true for rvalues (xvalues/prvalues), false for lvalues
