GPU/Accelerator
├── Team 0 (works on j = 0..chunk)
│   ├── Thread 0: SIMD processes i = 0,16,32... (vectorized)
│   ├── Thread 1: SIMD processes i = 1,17,33...
│   └── ...
├── Team 1 (works on j = chunk..2*chunk)
│   └── ...
└── ...
