#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/wait.h>

#define MAX_PATH 1024

// Function to check if a file exists
int file_exists(const char *path) {
    struct stat buffer;
    return (stat(path, &buffer) == 0);
}

// Function to execute a command and check return code
int execute_command(const char *cmd, int expect_success) {
    printf("Executing: %s\n", cmd);
    int ret = system(cmd);
    if (expect_success && ret != 0) {
        fprintf(stderr, "Command failed: %s\n", cmd);
        return 0;
    }
    return 1;
}

int main(int argc, char *argv[]) {
    char cwd[MAX_PATH];
    char gcov_dump_path[MAX_PATH];
    char dummy_prog_path[MAX_PATH];
    char dummy_gcda_path[MAX_PATH];
    char cmd[MAX_PATH * 2];
    
    // Get current working directory
    if (getcwd(cwd, sizeof(cwd)) == NULL) {
        perror("getcwd failed");
        return 1;
    }
    
    printf("Current directory: %s\n", cwd);
    
    // Step 1: Build instrumented gcov-dump if it doesn't exist
    // First check if we can find gcov-dump source
    const char *gcov_dump_source = "gcov-dump.cc";
    if (!file_exists(gcov_dump_source)) {
        // Try to find it in common locations
        if (file_exists("../../gcc/gcov-dump.cc")) {
            gcov_dump_source = "../../gcc/gcov-dump.cc";
        } else if (file_exists("../gcc/gcov-dump.cc")) {
            gcov_dump_source = "../gcc/gcov-dump.cc";
        } else {
            fprintf(stderr, "Could not find gcov-dump.cc\n");
            return 1;
        }
    }
    
    // Build instrumented gcov-dump
    snprintf(gcov_dump_path, sizeof(gcov_dump_path), "%s/gcov-dump-instrumented", cwd);
    
    if (!file_exists(gcov_dump_path)) {
        printf("Building instrumented gcov-dump...\n");
        
        // Try to find libiberty
        const char *libiberty_path = "../../libiberty/libiberty.a";
        if (!file_exists(libiberty_path)) {
            libiberty_path = "../libiberty/libiberty.a";
            if (!file_exists(libiberty_path)) {
                fprintf(stderr, "Could not find libiberty.a\n");
                return 1;
            }
        }
        
        // Build command
        snprintf(cmd, sizeof(cmd),
                 "g++ -O0 -fprofile-arcs -ftest-coverage -I. -I../../include -I../../libiberty "
                 "%s %s -o %s",
                 gcov_dump_source, libiberty_path, gcov_dump_path);
        
        if (!execute_command(cmd, 1)) {
            return 1;
        }
    } else {
        printf("Using existing instrumented gcov-dump\n");
    }
    
    // Step 2: Create a simple C program to generate GCOV data
    const char *dummy_c_content = 
        "#include <stdio.h>\n"
        "int main() {\n"
        "    int i;\n"
        "    for (i = 0; i < 10; i++) {\n"
        "        printf(\"Value: %d\\n\", i);\n"
        "    }\n"
        "    return 0;\n"
        "}\n";
    
    FILE *dummy_c = fopen("dummy.c", "w");
    if (!dummy_c) {
        perror("Failed to create dummy.c");
        return 1;
    }
    fputs(dummy_c_content, dummy_c);
    fclose(dummy_c);
    
    // Compile dummy program with coverage
    snprintf(dummy_prog_path, sizeof(dummy_prog_path), "%s/dummy_prog", cwd);
    snprintf(cmd, sizeof(cmd),
             "gcc -O0 -fprofile-arcs -ftest-coverage dummy.c -o %s",
             dummy_prog_path);
    
    if (!execute_command(cmd, 1)) {
        return 1;
    }
    
    // Run dummy program to generate .gcda file
    snprintf(cmd, sizeof(cmd), "%s", dummy_prog_path);
    if (!execute_command(cmd, 1)) {
        return 1;
    }
    
    // Set path to dummy.gcda
    snprintf(dummy_gcda_path, sizeof(dummy_gcda_path), "%s/dummy.gcda", cwd);
    
    if (!file_exists(dummy_gcda_path)) {
        fprintf(stderr, "Failed to generate dummy.gcda\n");
        return 1;
    }
    
    printf("Generated dummy.gcda at: %s\n", dummy_gcda_path);
    
    // Step 3: Execute gcov-dump with various flag combinations
    // First, clean any existing coverage data for gcov-dump
    printf("\nCleaning existing coverage data...\n");
    system("rm -f gcov-dump-instrumented.gcda gcov-dump-instrumented.gcno");
    system("rm -f gcov-dump.gcda gcov-dump.gcno");
    
    // Helper function to run gcov-dump and merge coverage
    void run_gcov_dump_test(const char *args, int expect_success) {
        char full_cmd[MAX_PATH * 3];
        
        // Run gcov-dump with given arguments
        snprintf(full_cmd, sizeof(full_cmd), "%s %s", gcov_dump_path, args);
        execute_command(full_cmd, expect_success);
        
        // Merge coverage data
        // First, find the .gcda file generated by this run
        snprintf(full_cmd, sizeof(full_cmd),
                 "find . -name '*.gcda' -newer %s -exec cp {} . \\; 2>/dev/null || true",
                 gcov_dump_path);
        system(full_cmd);
        
        // Generate intermediate coverage info
        snprintf(full_cmd, sizeof(full_cmd), "gcov -i gcov-dump.cc 2>/dev/null || true");
        system(full_cmd);
    }
    
    printf("\n=== Testing individual flags ===\n");
    
    // Test help flag
    printf("\n1. Testing -h (help flag):\n");
    run_gcov_dump_test("-h", 1);
    
    // Test version flag
    printf("\n2. Testing -v (version flag):\n");
    run_gcov_dump_test("-v", 1);
    
    // Test individual dump flags with data file
    printf("\n3. Testing -l flag:\n");
    run_gcov_dump_test("-l dummy.gcda", 1);
    
    printf("\n4. Testing -p flag:\n");
    run_gcov_dump_test("-p dummy.gcda", 1);
    
    printf("\n5. Testing -r flag:\n");
    run_gcov_dump_test("-r dummy.gcda", 1);
    
    printf("\n6. Testing -s flag:\n");
    run_gcov_dump_test("-s dummy.gcda", 1);
    
    printf("\n=== Testing combined flags ===\n");
    
    // Test space-separated combined flags
    printf("\n7. Testing -l -p -r -s (space separated):\n");
    run_gcov_dump_test("-l -p -r -s dummy.gcda", 1);
    
    // Test concatenated flags
    printf("\n8. Testing -lprs (concatenated):\n");
    run_gcov_dump_test("-lprs dummy.gcda", 1);
    
    // Test invalid flag (should trigger default case)
    printf("\n9. Testing -x (invalid flag, should trigger error):\n");
    run_gcov_dump_test("-x dummy.gcda", 0);
    
    // Step 4: Generate final coverage report
    printf("\n=== Generating final coverage report ===\n");
    
    // First, ensure we have all coverage data merged
    snprintf(cmd, sizeof(cmd), "gcov -i gcov-dump.cc 2>/dev/null || true");
    system(cmd);
    
    // Generate human-readable coverage report
    printf("\nGenerating coverage report for gcov-dump.cc:\n");
    snprintf(cmd, sizeof(cmd), "gcov -b gcov-dump.cc");
    system(cmd);
    
    // Also generate a simple text report showing executed lines
    printf("\n=== Checking target lines (111-130) coverage ===\n");
    snprintf(cmd, sizeof(cmd), 
             "gcov -l gcov-dump.cc | grep -A 20 -B 5 '^111\\|^112\\|^113\\|^114\\|^115\\|^116\\|"
             "^117\\|^118\\|^119\\|^120\\|^121\\|^122\\|^123\\|^124\\|^125\\|^126\\|^127\\|"
             "^128\\|^129\\|^130'");
    system(cmd);
    
    // Check if .gcov file was created and examine it
    if (file_exists("gcov-dump.cc.gcov")) {
        printf("\n=== Summary from gcov-dump.cc.gcov ===\n");
        snprintf(cmd, sizeof(cmd),
                 "grep -n '^[[:space:]]*1[1-9][0-9]:' gcov-dump.cc.gcov | "
                 "grep -E '(111|112|113|114|115|116|117|118|119|120|"
                 "121|122|123|124|125|126|127|128|129|130):'");
        system(cmd);
        
        // Count how many of our target lines were executed
        printf("\n=== Coverage statistics for target switch block ===\n");
        snprintf(cmd, sizeof(cmd),
                 "awk '/^[[:space:]]*1[1-9][0-9]:/ { "
                 "if ($1 ~ /111:|112:|113:|114:|115:|116:|117:|118:|119:|120:|"
                 "121:|122:|123:|124:|125:|126:|127:|128:|129:|130:/) { "
                 "if ($1 ~ /#####/) { not_covered++ } else { covered++ } "
                 "total++ } } "
                 "END { printf \"Covered: %%d/%%d lines\\n\", covered, total }' "
                 "gcov-dump.cc.gcov");
        system(cmd);
    }
    
    // Cleanup
    printf("\n=== Cleaning up temporary files ===\n");
    remove("dummy.c");
    remove(dummy_prog_path);
    remove(dummy_gcda_path);
    remove("dummy.gcno");
    
    printf("\nTest completed. Check the coverage output above to verify that\n");
    printf("lines 111-130 in gcov-dump.cc have been executed.\n");
    
    return 0;
}
