Device (e.g., GPU)
├── Team 0 (threads)
│   ├── SIMD lane 0: i=0, i=16, i=32...
│   ├── SIMD lane 1: i=1, i=17, i=33...
│   └── ...
├── Team 1 (threads)
│   ├── SIMD lane 0: i=0, i=16, i=32...
│   └── ...
└── ...
