Device (e.g., GPU)
├── Team 0: j = 0..k
│   ├── Thread 0: j = 0
│   │   └── Vectorized: i = 0..15, 16..31, ...
│   ├── Thread 1: j = 1
│   │   └── Vectorized: i = 0..15, 16..31, ...
│   └── ...
├── Team 1: j = k+1..2k
│   └── Similar pattern
└── ...
