/* test_gcc_driver_cleanup.c
 * This test triggers the GCC driver's cleanup routine by invoking it
 * with various flags that set the state variables being reset.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>

#define SIMPLE_C_CONTENT "int main(void) { return 0; }\n"
#define SIMPLE_C_FILENAME "simple_test_file.c"

/* Create a simple C source file for testing */
static int create_test_file(void) {
    FILE *f = fopen(SIMPLE_C_FILENAME, "w");
    if (!f) {
        perror("Failed to create test file");
        return 0;
    }
    fputs(SIMPLE_C_CONTENT, f);
    fclose(f);
    return 1;
}

/* Clean up generated files */
static void cleanup_generated_files(void) {
    /* Remove common temp files generated by -save-temps */
    remove("test_output.o");
    remove("fail_output.o");
    remove("simple_test_file.i");
    remove("simple_test_file.s");
    remove("coverage_test.i");
    remove("coverage_test.s");
    remove("fail_test.i");
    remove("fail_test.s");
    
    /* Remove test source file */
    remove(SIMPLE_C_FILENAME);
    
    /* Remove potential dumpdir directories */
    system("rm -rf ./test_artifacts 2>/dev/null");
    system("rm -rf ./fail_artifacts 2>/dev/null");
}

/* Run a GCC command and capture its exit status */
static int run_gcc_command(const char *cmd) {
    printf("Running: %s\n", cmd);
    int status = system(cmd);
    
    if (WIFEXITED(status)) {
        printf("Exit status: %d\n\n", WEXITSTATUS(status));
        return WEXITSTATUS(status);
    } else {
        printf("Command terminated abnormally\n\n");
        return -1;
    }
}

int main(void) {
    int overall_result = 0;
    
    /* Create test directory for dumpdir */
    mkdir("./test_artifacts", 0755);
    mkdir("./fail_artifacts", 0755);
    
    /* Create the simple C source file */
    if (!create_test_file()) {
        return 1;
    }
    
    printf("=== Testing GCC Driver Cleanup Routine ===\n\n");
    
    /* INVOCATION A: Sets state with -save-temps, -dumpdir, -dumpbase, -o
     * This should succeed and trigger cleanup with allocated state */
    printf("1. Testing successful compilation with state variables set:\n");
    const char *cmd_a = "gcc -save-temps -dumpdir ./test_artifacts "
                       "-dumpbase coverage_test -o test_output.o -c " 
                       SIMPLE_C_FILENAME;
    run_gcc_command(cmd_a);
    
    /* INVOCATION B: Sets state but causes backend failure
     * Uses invalid architecture to fail after driver initialization */
    printf("2. Testing failed compilation with state variables set:\n");
    const char *cmd_b = "gcc -save-temps -dumpdir ./fail_artifacts "
                       "-dumpbase fail_test -o fail_output.o "
                       "-march=invalid-arch " SIMPLE_C_FILENAME;
    run_gcc_command(cmd_b);
    
    /* INVOCATION C: Tests with -specs and -V flags
     * These influence spec_machine and print_version */
    printf("3. Testing with -specs and -V flags:\n");
    const char *cmd_c = "gcc -specs=nosuch.spec -V " SIMPLE_C_FILENAME " 2>&1";
    run_gcc_command(cmd_c);
    
    /* INVOCATION D: Tests -Werror turning warnings into errors
     * This affects greatest_status */
    printf("4. Testing -Werror with deliberate warning:\n");
    /* First create a file with a warning */
    FILE *f = fopen("warn.c", "w");
    if (f) {
        fputs("int main(void) { int x; return 0; } /* unused variable */\n", f);
        fclose(f);
        const char *cmd_d = "gcc -Werror -c warn.c 2>&1";
        run_gcc_command(cmd_d);
        remove("warn.c");
    }
    
    /* INVOCATION E: Tests verbose flag and other state variables */
    printf("5. Testing verbose flag and help:\n");
    const char *cmd_e = "gcc -v -c " SIMPLE_C_FILENAME " 2>&1";
    run_gcc_command(cmd_e);
    
    /* INVOCATION F: Tests with different -save-temps variants */
    printf("6. Testing different -save-temps options:\n");
    const char *cmd_f = "gcc -save-temps=cwd -dumpbase base_test -c " 
                       SIMPLE_C_FILENAME;
    run_gcc_command(cmd_f);
    
    /* INVOCATION G: Tests dumpdir with trailing slash handling */
    printf("7. Testing dumpdir with trailing slash:\n");
    const char *cmd_g = "gcc -save-temps -dumpdir ./test_artifacts/ "
                       "-dumpbase slash_test -c " SIMPLE_C_FILENAME;
    run_gcc_command(cmd_g);
    
    /* INVOCATION H: Tests multiple output base options */
    printf("8. Testing multiple output-related options:\n");
    const char *cmd_h = "gcc -save-temps -dumpdir ./test_artifacts "
                       "-dumpbase multi_test -dumpbase-ext .ext "
                       "-o multi_output.o -c " SIMPLE_C_FILENAME;
    run_gcc_command(cmd_h);
    
    /* Clean up generated files */
    cleanup_generated_files();
    
    printf("=== Test completed ===\n");
    printf("All GCC invocations attempted. Check coverage data for gcc.cc.\n");
    
    return overall_result;
}
