Device (e.g., GPU)
├── Team 0 (Thread Block 0)
│   ├── Thread 0: processes j=0, then SIMD vector for i=0..15
│   ├── Thread 1: processes j=1, then SIMD vector for i=0..15
│   └── ...
├── Team 1 (Thread Block 1)
│   └── ...
└── ...
