Before:                    After:
  jump L1                  jump L1
  nop                      insn_X   # moved from L1
  ...                      ...
L1:                        ...
  insn_X                   ...
