Device (e.g., GPU)
├── Team 0: j = 0..(N/num_teams - 1)
│   ├── Thread 0: SIMD vector of i values (vector length ≤ 16)
│   ├── Thread 1: SIMD vector of i values
│   └── ...
├── Team 1: j = (N/num_teams)..(2N/num_teams - 1)
│   └── ...
└── ...
