Device (e.g., GPU)
├── Team 0 (threads)
│   ├── j = 0..k
│   │   ├── SIMD vector lane 0: i = 0, 16, 32...
│   │   ├── SIMD vector lane 1: i = 1, 17, 33...
│   │   └── ...
│   └── ...
├── Team 1 (threads)
│   └── j = k+1..m
└── ...
