Device (e.g., GPU)
├── Team 0
│   ├── Threads process: j = 0, 1, 2...
│   │   └── Each thread uses SIMD for inner i-loop
├── Team 1
│   ├── Threads process: j = next chunk...
│   │   └── Each thread uses SIMD for inner i-loop
└── ...
