Device (e.g., GPU)
├── Team 0 (Thread Block 0)
│   ├── Thread 0: processes i=0..15, i=32..47, ... (SIMD)
│   ├── Thread 1: processes i=16..31, i=48..63, ... (SIMD)
│   └── ...
├── Team 1 (Thread Block 1)
│   └── ...
└── ...
